development:
  sessions:
    default:
      database: ndc
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false
production:
  sessions:
    default:
      database: ndc
      hosts:
        - localhost:27017
      options:
        raise_not_found_error: false
        identity_map_enabled: true
